### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by fingdo** [maning0303/CrashMonitor#1]
1，长截图可以选择是否加入，毕竟加入了读写本地文件夹的权限。
2，为何需要相机权限，是否忘记移除？
3，为何minSDK是16，里面最低的statusbar的api最低是14。如果想要更多人使用，应该可以去掉无用的沉浸状态栏的工具类，最低api可以为11
4，可以设置错误日志的目录，默认为本应用的cache文件夹
5，错误日志的列表优化，
标题显示报错时间和错误类型，比如NullPointExpection 
内容可以显示用户可以设置高亮或加粗显示的报错的多个包名，例如：com.xx.aaa,com.xx.bb之类的。
6，详情同理可以设置高亮或加粗显示的报错的多个包名的行数

**Comment by maning0303** [comment]
@fingdo 
1.有一个截图功能是滚动截图，出来也算是长截图；
2.相机权限应该是忘记删除了，后面会删除；
3.多余代码会做一次优化，minSDK可以降低的；
4.日志的保存目录默认就是在应用的Cache文件夹中；
5.后期会考虑列表优化
感谢提出的建议。

**Comment by fingdo** [comment]
1的意思我可能描述不清楚，是截图可以提供代码开关，用户可以选择是否开启此功能

**Comment by fingdo** [comment]
4的意思是，默认为本应用的cache目录，这个我看了源码。但是用户使用可以通过代码设置自定义的日志目录

**Comment by maning0303** [comment]
@fingdo 了解了，感谢这些建议。

**Comment by maning0303** [comment]
@fingdo 新版本更新了，你可以看看，修改了文件命名和部分高亮显示；截图功能暂时没有动态配置，以后可能考虑；自定义的日志目录这个功能暂时也还没有做，后期可以考虑添加，主要考虑到权限问题。感谢你的建议。
