### ISSUE TITLE
崩溃日志列表物理返回键闪退

### ISSUE THREAD

**Issue by 361635769** [maning0303/CrashMonitor#3]
在崩溃日志列表界面点击返回键闪退，日志详情界面点击分享闪退

**Comment by maning0303** [comment]
@361635769 请问一下，有没有崩溃日志贴出来一下?

**Comment by maning0303** [comment]
@361635769 新版本更新了，分享闪退的问题修复，物理键返回暂时没有发现，你看看你那边有没有具体的日志提供一下。
